apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: production
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000  # same as containerPort above
  type: NodePort  # Change to LoadBalancer if using cloud LB
